spring:
  application:
    name: token-exchange
  security:
    oauth2:
      client:
        registration:
          mobile:
            provider: mobile
            client-id: mobile
            client-name: "Mobile"
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - admin
        provider:
          mobile:
            issuer-uri: http://localhost:9090
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090

server:
  port: 7171

logging:
  level:
    org.springframework.security: trace

jwt:
  key:
    id: local
    rsa-public: classpath:keys/public.pem
    rsa-private: classpath:keys/key.pem
