server:
  port: 7070
spring:
  application:
    name: resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
logging:
  level:
    org.springframework.security: trace
