version: "3"
services:
  authorization_server:
    profiles:
      - "oauth2_server"
    platform: linux/amd64
    image: mysql:8.0.23
    container_name: oauth2_server_database
    environment:
      MYSQL_DATABASE: oauth2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "${HOST_PORT:-3310}:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  client:
    profiles:
      - "oauth2_client"
    platform: linux/amd64
    image: mysql:8.0.23
    container_name: oauth2_client_database
    environment:
      MYSQL_DATABASE: client
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "${HOST_PORT:-3311}:3306"
