server:
  port: 8080
spring:
  application:
    name: client
  security:
    oauth2:
      client:
        registration:
          spotify:
            provider: spotify
            client-id: spotify
            client-secret: password
            client-name: "Spotify"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - admin
          slack:
            provider: slack
            client-id: slack
            client-secret: secret
            client-name: "Slack"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - admin
        provider:
          spotify:
            issuer-uri: http://localhost:9090
          slack:
            issuer-uri: http://localhost:9090

logging:
  level:
    org.springframework.security: trace
